### ISSUE TITLE
FIxed Modification at N-term

### ISSUE THREAD

**Issue by alessandro-vai** [bibs-lab/SpecGlobX#1]
Hello!

I am super interested in testing your tool. However, I need to specify a fixed modification at N-term. Is this possible? I found only the possibility to add a mass on to specific amino acid..

Thank you
Alessandro

**Comment by dominique-tessier** [comment]
Hi Alessandro,

  Thanks a lot for your interest in SpecGlobX. Currently, I confirm it is not possible to add a fixed modification on the N-Term/C-Term. I'm going to evaluate if this option can be quickly implemented. I'll get back to you to let you know whether I'll support it in the next release.

**Comment by dominique-tessier** [comment]
With the latest release (1.0.3), you can specify a fixed modification on the NTer or CTer. For that, you need to add lines in the config.properties file:
sg.modif.NT=<value>
sg.modif.CT=<value>

We welcome your feedback if there is any issue when specifying those fixed modifications.
